/**
 * Session Engine — Internal Types
 *
 * These types are the contract between the reducer, summary builder,
 * and any consumer (UI or test). Do not import directly from this file
 * outside the session feature — use the public API in index.ts.
 */

import type { Difficulty, Problem, SessionConfig, SessionSummary, SessionType } from '@/shared/types'

// ── Answered problem record ───────────────────────────────────────────────────

/** A problem that the user has already responded to. */
export interface AnsweredProblem {
  problem: Problem
  userAnswer: number
  correct: boolean
  /** Time from problem display to answer submission in ms. */
  timeMs: number
}

// ── Session state ─────────────────────────────────────────────────────────────

export type SessionStatus = 'idle' | 'running' | 'evaluating' | 'complete'

export interface SessionState {
  status: SessionStatus
  config: SessionConfig
  /** Full problem queue injected at start.
   *  Drill: exactly problemCount items.
   *  Challenge: a long pre-generated queue (timer, not exhaustion, ends it). */
  problems: Problem[]
  /** Index into `problems` for the current (or next) problem. */
  currentIndex: number
  /** Timestamp (ms) when the current problem was displayed.
   *  Used to compute timeMs on submitAnswer. */
  problemStartedAt: number
  /** Completed answers, in order. */
  answers: AnsweredProblem[]
  /** Correct-answer streak for the current session. Resets on wrong answer. */
  streak: number
  /** Milliseconds remaining (challenge mode only; -1 for drill). */
  timeRemainingMs: number
  /** Populated once status === 'complete'. */
  summary: SessionSummary | null
}

// ── Actions ───────────────────────────────────────────────────────────────────

/** Start a new session. Problems must be pre-generated by the caller. */
export interface StartAction {
  type: 'start'
  config: SessionConfig
  problems: Problem[]
  /** Current timestamp in ms (injected for deterministic tests). */
  now: number
}

/** User submits an answer for the current problem. */
export interface SubmitAnswerAction {
  type: 'submitAnswer'
  answer: number
  /** Current timestamp in ms. */
  now: number
}

/**
 * Advance from 'evaluating' to the next problem (or 'complete' if the
 * drill queue is exhausted). The UI calls this after the feedback delay.
 */
export interface AdvanceAction {
  type: 'advance'
  /** Current timestamp in ms (marks when the next problem is displayed). */
  now: number
}

/**
 * Clock tick for challenge mode. The caller (UI timer or test) fires this
 * periodically. The reducer decrements timeRemainingMs and transitions to
 * 'complete' when it reaches 0.
 *
 * @param elapsedMs  Milliseconds since the last tick (typically ~100–1000ms).
 */
export interface TickAction {
  type: 'tick'
  elapsedMs: number
}

export type SessionAction = StartAction | SubmitAnswerAction | AdvanceAction | TickAction

// ── Initial state factory ─────────────────────────────────────────────────────

export function createIdleState(): SessionState {
  return {
    status: 'idle',
    config: { type: 'drill', techniqueId: '' },
    problems: [],
    currentIndex: 0,
    problemStartedAt: 0,
    answers: [],
    streak: 0,
    timeRemainingMs: -1,
    summary: null,
  }
}
